### ISSUE TITLE
YAML file error: tuple index out of range

### ISSUE THREAD

**Issue by danfinn** [sillygoose/sbhistory#1]
I recently got the password to my SunnyBoy 7.0 inverter and was hoping to play with the grafana dashboards you have created.  I didn't make it very far though, I'm getting the following error when running sbhistory:

`python3 sbhistory/sbhistory.py
YAML file error: tuple index out of range`

I get this with your default sample_secrets.yaml file copied to .sbhistory_secrets.yaml

`python3 --version
Python 3.9.10`

**Comment by danfinn** [comment]
Thanks @sillygoose.  For testing purposes is it possible to just see if it will connect to the inverter and return data, without needing the influx db?  Is it as simple as commenting those out from the secrets file?

**Comment by sillygoose** [comment]
I little more complicated but I made the changes.

Pull the new updates and set the InfluxDB `enabled` option to False in the YAML file.

**Comment by danfinn** [comment]
Awesome, thanks!  I'll try to test this out later today or tomorrow and let you know how it goes.

**Comment by danfinn** [comment]
I got it to run however it doesn't seem to be doing much.  This is what I got for output:

 python3 sbhistory/sbhistory.py
[2022-03-24 08:12:44,476] [logfiles] [INFO] Created application log /Users/dfinn/git/sbhistory/log/sbhistory_2022-03-24.log
[2022-03-24 08:12:44,560] [sbhistory] [INFO] sbhistory inverter utility 1.1.3.dev, PID is 88671
[2022-03-24 08:12:44,579] [influx] [INFO] The InfluxDB database is disabled
[2022-03-24 08:12:44,579] [sbhistory] [INFO] Closing sbhistory application

**Comment by sillygoose** [comment]
Did you enable any of the options in there YAML file?

  production:
    enable: False
    start: '2022-03-01'
    stop: '2022-03-12'

  daily_history:
    enable: False
    start: '2022-03-10'

  fine_history:
    enable: False
    start:  '2022-03-01'

  irradiance:
    enable: False
    start:  '2022-03-01'

**Comment by sillygoose** [comment]
A quick way to print is add this print statement to the write_points() function in influx.py:

    def write_points(self, points):
        if not self._enabled:
            print(points) ###
            return True

You will get InfluxDB line protocol output which is just an ASCII string (I added newlines to this output for clarity):
```
[
'production,_inverter=sb71 year=1695.298 1641013200',
'production,_inverter=sb72 year=1650.204 1641013200',
'production,_inverter=sb51 year=1085.798 1641013200',
'production,_inverter=site year=4431.3 1641013200'
]
```
I have 3 inverters so I get one line for each inverter and the site value (4432kWh so far).  You will just get one but can you pick out the production values for the selected days, months, and year and compare to inverter login or the sunnyportal.com results.

**Comment by sillygoose** [comment]
Are you all set so I can close this?

**Comment by danfinn** [comment]
Yes, I haven't actually had a chance to mess with it anymore but it does seem to be connecting at this point.  
Thanks,Dan
    On Wednesday, March 30, 2022, 12:51:58 PM MDT, Rick ***@***.***> wrote:  
 
 


Are you all set so I can close this?
